---

- name: /etc/apt/sources.list
  copy:
    content: |
      # debian {{ ansible_distribution_release }} sources.list
      deb http://deb.debian.org/debian/ {{ ansible_distribution_release }} main contrib non-free non-free-firmware
      deb http://security.debian.org/debian-security {{ ansible_distribution_release }}-security main contrib non-free non-free-firmware
      deb http://deb.debian.org/debian/ {{ ansible_distribution_release }}-updates main contrib non-free non-free-firmware
      #deb http://deb.debian.org/debian/ {{ ansible_distribution_release }}-proposed-updates main contrib non-free non-free-firmware
      deb http://deb.debian.org/debian/ {{ ansible_distribution_release }}-backports main contrib non-free non-free-firmware

    dest: /etc/apt/sources.list
    mode: 0644
