---

- name: Internet
  apt:
    state: present
    name:
    # Navigateur web
    - firefox-esr
    - firefox-esr-l10n-fr
    - chromium
    - chromium-l10n
    # Client messagerie
    - thunderbird
    - thunderbird-l10n-fr
    # qr code wifi
    - wifi-qr

# deb12 à tester
- name: Internet | Extensions Navigateur
  apt:
    state: present
    name:
    - webext-ublock-origin-firefox
    - webext-ublock-origin-chromium
    - webext-privacy-badger
    - webext-bulk-media-downloader
    
- name: Internet | téléchargement audio video yt-dlp
  apt:
    state: latest
    name:
    - yt-dlp
    - youtubedl-gui
    default_release: "{{ ansible_distribution_release }}-backports"
