---

- name: Spotify | import apt key
  apt_key:
    url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
    state: present

- name: Spotify | depot
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    filename: spotify
    state: present

- name: Spotify | install spotify-client
  apt:
    name: spotify-client
