---

- name: Allow release-info to change for APT repositories
  shell: apt-get update -y --allow-releaseinfo-change
  changed_when: false
  #~ args:
    #~ warn: false
  
#~ - name: Allow release info change NE MARCHE PAS
  #~ lineinfile:
    #~ path: /etc/apt/apt.conf.d/99releaseinfochange
    #~ state: present
    #~ create: yes
    #~ line: Acquire::AllowReleaseInfoChange::Suite "true";
        
- name: Update and upgrade apt packages
  apt:
    upgrade: dist
    update_cache: yes
