#!/bin/sh
 
chown root: /etc/sudoers.d/90user-mount

# Ajout pam_exec.so
sed -i -e "/pam_exec.so/d" /etc/pam.d/common-auth
echo "auth	optional	pam_exec.so expose_authtok /usr/local/bin/cred-user-mount" | tee -a /etc/pam.d/common-auth
